import "./globals.css";
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import AppSidebar from "@/components/AppSidebar";
import QueryProvider from "@/providers/QueryProvider";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${poppins.variable} antialiased flex`}>
        <SidebarProvider>
          <div className="flex w-full min-h-screen">
            <AppSidebar />
            <main className="flex flex-col w-full">
              <header className="p-4 border-b">
                <SidebarTrigger />
              </header>
              <div className="flex-grow">
                <QueryProvider>{children}</QueryProvider>
              </div>
            </main>
          </div>
        </SidebarProvider>
      </body>
    </html>
  );
}
